### ISSUE TITLE
[Feature] Provide the ability to set lua variables without using closures

### ISSUE THREAD

**Issue by neon-mmd** [metaworm/ezlua#2]
Provide support for having the ability to set lua variables from rust without using closures because I think making closure free will make using your crate easier, even beginners would be able to use it without the need of knowing closures :slightly_smiling_face: and also this will make your project more unique than previous lua-rust communication crates because they all use closures in some way or the other while if you make your's closure free it will make your project stand out :slightly_smiling_face: . 

Also, one suggestion if you don't mind. I think the project description could be improved I feel it is not descriptive enough I think maybe you could put it like this `An alternative to mlua which provides fast, ergonomic and zero-cost rust bindings for Lua`, Also below description add some labels this will make your repository more discoverable like there are many guys who search GitHub using these labels when they will find your project with this labels and if they found it interesting they will start contributing to your project :slightly_smiling_face:  .

**Comment by metaworm** [comment]
I don't quite understand what you mean by not using closures. Can you give me some examples?

If you mean the function that binds rust to lua to avoid the overhead of closures, ezlua now supports it. The rust closure without capturing variables is equivalent to an ordinary function, and the binding generated by ezlua is also an ordinary function.

**Comment by neon-mmd** [comment]
> I don't quite understand what you mean by not using closures. Can you give me some examples?

Sure!! :slightly_smiling_face:  Here is an example of what I want to have :point_down: .

Like maybe having instead of this:

``` lua
lua.global().set("add", lua.new_closure(|a: u32, b: u32| a + b)?)?;
lua.do_string("assert(add(111, 222) == 333)", None)?;
```

Something like having a `stringbuilder` kind of thing:

``` rust
lua.global().set("add", 
 r#"
               function add (x, y)
                    return x + y
               end
"#
)?;

lua.do_string("assert(add(111, 222) == 333)", None)?;
```

**Comment by neon-mmd** [comment]
My bad (Sorry), Now after scanning through the examples a few more times I got it, you do support string builder I thought you don't :smile: but anyways your project really looks great like it provides so much cool stuff like you have so many features which I think even rlua or mlua doesn't provide it yet so good luck for your project :+1:, Just that I am waiting for it be supported on `stable` compiler because my project uses stable version. I hope this project grows because I see lots of potential in this project :slightly_smiling_face:  .
