### ISSUE TITLE
Ability to make lua libraries

### ISSUE THREAD

**Issue by lenscas** [metaworm/ezlua#3]
I think it would be great if ezlua was able to be used to create libraries as well. Right now, mlua is pretty much the only option for that.

**Comment by metaworm** [comment]
This is not difficult, and it is already supported now.

In the next version, I will add a macro to simplify it.

**Comment by lenscas** [comment]
Oh. Neat. Didn't see it in the list of features. Must have missed it then I guess.

**Comment by metaworm** [comment]
No, I really didn't write this. Can you take a look at my [next implementation to be released](https://github.com/metaworm/ezlua/blob/3c2c15c7f13541f995d1af19dfbaa1820bfd6eb5/src/macros.rs#L3)

**Comment by metaworm** [comment]
Now, you can try this method to make lua library with using ezlua 0.2.2

First, disable the default vendored feature, and keep std feature only, and config your crate as a cdylib
```toml
[dependencies]
ezlua = {version = '0.2.2', default-features = false, features = ['std']}

[lib]
crate-type = ['cdylib']
```

Then, export your luaopen function by using `ezlua::lua_module!` macro, Where the first argument is `luaopen_<Your module name>`
```rust
use ezlua::prelude::*;

ezlua::lua_module!(luaopen_mymod, |lua| {
    let module = lua.new_table()?;

    module.set("_VERSION", "0.1.0")?;
    // ... else module functions

    return Ok(module);
});
```

**Comment by lenscas** [comment]
haven't tested it but sounds like it does exactly what I wanted.
